### ISSUE TITLE
Procedural Generation

### ISSUE THREAD

**Issue by baldurfb** [baldurfb/ShapeShifter#5]
Núna erum við með prufusenu sem er byggð úr unity glugganum. Við viljum búa til leikinn úr kóðanum. Ég er að búa til GameMaster klasan sem mun byggja heiminn frá grunni úr C#. Svo getur InputManager og aðrir klasar unnið með gögnin þaðan í staðin fyrir að leita að þeim frá unity og halda sína eigin skrá.

**Comment by BFB1** [comment]
Test scene er komið í Awake() fyrir GameMaster og er búið til úr kóða.

**Comment by baldurfb** [comment]
Nú byggir GameMaster heiminn. Hann bætir flugvélum og stöðvum við dynamically miðað við hversu vel spilaranum gengur.
